## Universal function 

or ufunc is a function that performs element-wise operations on data in ndarrays


In [3]:
#Many ufunc are simple element-wise transformations
# sqrt or exp => unary functions
# add or maximum uses 2 array => binary ufuncs

import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
x = np.random.randn(8)
y = np.random.randn(8)

In [7]:
x

array([-0.22316773, -1.92596547, -0.2697711 , -0.89031272, -0.32108617,
        0.06206677, -1.02933843,  0.54646953])

In [8]:
y

array([ 0.82024946, -1.81437763,  0.07125545, -1.07904396,  0.11037115,
       -0.33687866, -0.27137449, -0.72782388])

In [9]:
np.maximum(x, y)

#numpy.maximum computed the element-wise maximum

array([ 0.82024946, -1.81437763,  0.07125545, -0.89031272,  0.11037115,
        0.06206677, -0.27137449,  0.54646953])

In [12]:
# ufunc can return multiple arrays
#modf is 1 example
#a vectorised version of python divmod
#returns the fractional and integral parts of a floating point array

arr = np.random.randn(7)*5
arr

array([-2.65054095,  0.98749969,  2.94121348, -3.79873065,  0.35584829,
       -5.08423281,  4.14240457])

In [14]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.65054095,  0.98749969,  0.94121348, -0.79873065,  0.35584829,
       -0.08423281,  0.14240457])

In [15]:
whole_part

array([-2.,  0.,  2., -3.,  0., -5.,  4.])

In [19]:
#Ufuncs accept an optional out argument 
#that allows them to operate in-place of array

arr

array([       nan, 0.99373019, 1.71499664,        nan, 0.59653021,
              nan, 2.0352898 ])

In [17]:
np.sqrt(arr)

C:\Users\daphnekyx\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 0.99373019, 1.71499664,        nan, 0.59653021,
              nan, 2.0352898 ])

In [18]:
np.sqrt(arr,arr)

C:\Users\daphnekyx\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 0.99373019, 1.71499664,        nan, 0.59653021,
              nan, 2.0352898 ])

In [ ]:
arr