- Linear algebra have matrix multiplication ...etc
- function work at element-wise basis

In [1]:
import numpy as np

x = np.array([[1., 2., 3. ], [ 4., 5., 6.]])

y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [2]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [5]:
#multiplication between matrix

# x.dot(y) is equivalent to np.dot(x, y)
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [7]:
#matrix product between 2-d array & 1-d array results in 1-d array

np.dot(x, np.ones(3))

array([ 6., 15.])

In [4]:
# @ acts as infix operator that performs matrix multiplication

x @ np.ones(3)

array([ 6., 15.])

In [5]:
# numpy.linalg has a standard set of matrix decompositions 
# like inverse and determinant

from numpy.linalg import inv, qr

X = np.random.randn(5, 5)


#computes dot product of X with transpose of T X.T.
mat = X.T.dot(X)
inv(mat)

array([[ 0.89501692,  0.64533845,  0.39721367,  0.22719829,  0.13609919],
       [ 0.64533845,  1.28525461,  0.03898148, -0.03595251,  0.3318396 ],
       [ 0.39721367,  0.03898148,  0.9090585 ,  0.33200699, -0.12977829],
       [ 0.22719829, -0.03595251,  0.33200699,  0.2330168 , -0.05814339],
       [ 0.13609919,  0.3318396 , -0.12977829, -0.05814339,  0.22821096]])

In [6]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  6.83952088e-17, -1.05104801e-16,
        -3.70151930e-17,  3.94373707e-17],
       [ 5.40961138e-17,  1.00000000e+00,  5.74995882e-17,
         4.48819529e-17, -1.77401581e-16],
       [ 3.76575459e-17, -3.98915415e-17,  1.00000000e+00,
        -2.71958897e-16,  9.96267016e-17],
       [ 1.49970509e-17, -1.63411158e-17, -1.14520474e-16,
         1.00000000e+00,  1.65972014e-16],
       [ 6.19861607e-17, -7.53396349e-17,  3.04910405e-16,
        -2.35598685e-17,  1.00000000e+00]])

In [7]:
q, r = qr(mat)

In [8]:
r

array([[-4.87585992,  2.66219188, -1.55405079, 10.53278351,  1.45235374],
       [ 0.        , -2.63256426,  2.12512776, -1.63375839,  8.33403042],
       [ 0.        ,  0.        , -3.37021292,  7.29835322,  0.17367243],
       [ 0.        ,  0.        ,  0.        , -2.19307913, -0.55566564],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.23081052]])

In [9]:
q

array([[-6.72558077e-01, -9.16974605e-02,  3.43115361e-01,
        -5.73889460e-01,  3.03611504e-01],
       [ 3.17703793e-01, -4.76375682e-01, -3.36138614e-01,
        -1.05545168e-01,  7.40271274e-01],
       [ 6.27686666e-02,  2.05248760e-01, -6.63155300e-01,
        -6.56004269e-01, -2.89510774e-01],
       [ 6.50415533e-01, -6.50573519e-02,  5.71606763e-01,
        -4.78716000e-01, -1.29706881e-01],
       [ 1.40533487e-01,  8.47524792e-01,  5.26634401e-02,
         7.04062118e-04,  5.09095406e-01]])